#!/bin/bash

echo "🧪 NEUPC Extension Quick Test Guide"
echo "===================================="
echo ""
echo "📂 Extension Path:"
echo "   /home/eyasir329/Documents/GitHub/neupc/browser-extension"
echo ""
echo "🌐 Load in Chrome:"
echo "   1. Open: chrome://extensions"
echo "   2. Enable 'Developer mode' (top right)"
echo "   3. Click 'Load unpacked'"
echo "   4. Select the browser-extension folder"
echo ""
echo "🦊 Load in Firefox:"
echo "   1. Open: about:debugging#/runtime/this-firefox"
echo "   2. Click 'Load Temporary Add-on'"
echo "   3. Select manifest.json from browser-extension folder"
echo ""
echo "🔍 Test URLs:"
echo "   Codeforces: https://codeforces.com/contest/1/submission/1"
echo "   AtCoder:    https://atcoder.jp/contests/abc001/submissions/1"
echo "   DMOJ:       https://dmoj.ca/submission/1"
echo "   LeetCode:   https://leetcode.com/submissions/detail/1/"
echo ""
echo "✅ What to Check:"
echo "   1. Open browser console (F12)"
echo "   2. Look for: [NEUPC:platform] Initialized"
echo "   3. Look for: [NEUPC:platform] Extracted submission: {...}"
echo "   4. No red errors in console"
echo ""
echo "📋 Full guide: browser-extension/TEST-NOW.md"
echo ""
