-- Seed platforms table with all supported competitive programming platforms
-- This ensures all platforms defined in problem-solving-platforms.js exist in the database

INSERT INTO public.platforms (code, name, profile_url_template, is_active) VALUES
('codeforces', 'Codeforces', 'https://codeforces.com/profile/{handle}', true),
('atcoder', 'AtCoder', 'https://atcoder.jp/users/{handle}', true),
('leetcode', 'LeetCode', 'https://leetcode.com/{handle}', true),
('toph', 'Toph', 'https://toph.co/u/{handle}', true),
('cses', 'CSES', 'https://cses.fi/user/{handle}', true),
('codechef', 'CodeChef', 'https://www.codechef.com/users/{handle}', true),
('topcoder', 'TopCoder', 'https://www.topcoder.com/members/{handle}', true),
('hackerrank', 'HackerRank', 'https://www.hackerrank.com/profile/{handle}', true),
('kattis', 'Kattis', 'https://open.kattis.com/users/{handle}', true),
('lightoj', 'LightOJ', 'https://lightoj.com/user/{handle}', true),
('uva', 'UVA', 'https://uhunt.onlinejudge.org/id/{handle}', true),
('spoj', 'SPOJ', 'https://www.spoj.com/users/{handle}', true),
('vjudge', 'VJudge', 'https://vjudge.net/user/{handle}', true),
('cfgym', 'CF Gym', 'https://codeforces.com/profile/{handle}', true),
('csacademy', 'CS Academy', 'https://csacademy.com/user/{handle}', true),
('eolymp', 'E-Olymp', 'https://www.eolymp.com/en/users/{handle}', true),
('usaco', 'USACO', 'https://usaco.org/', true),
('hackerearth', 'HackerEarth', 'https://www.hackerearth.com/@{handle}', true),
('dmoj', 'DMOJ', 'https://dmoj.ca/user/{handle}', true),
('googlecodejam', 'Google Code Jam', 'https://codingcompetitions.withgoogle.com/profile/{handle}', true),
('facebookhackercup', 'Facebook Hacker Cup', 'https://www.facebook.com/codingcompetitions/hacker-cup/', true),
('geeksforgeeks', 'GeeksforGeeks', 'https://auth.geeksforgeeks.org/user/{handle}', true),
('codingame', 'CodinGame', 'https://www.codingame.com/profile/{handle}', true),
('beecrowd', 'Beecrowd', 'https://judge.beecrowd.com/en/profile/{handle}', true),
('luogu', 'Luogu', 'https://www.luogu.com.cn/user/{handle}', true),
('nowcoder', 'NowCoder', 'https://ac.nowcoder.com/acm/user/{handle}', true),
('codedrills', 'CodeDrills', 'https://codedrills.io/users/{handle}', true),
('yandex', 'Yandex Contest', 'https://yandex.com/cup/profile/{handle}', true),
('nerc', 'NERC/ITMO', 'https://nerc.itmo.ru/user/{handle}', true),
('tlx', 'TLX/TOKI', 'https://tlx.toki.id/profiles/{handle}', true),
('yukicoder', 'Yukicoder', 'https://yukicoder.me/users/{handle}', true),
('acmp', 'ACMP', 'https://acmp.ru/index.asp?main=user&id={handle}', true),
('timus', 'Timus Online Judge', 'https://acm.timus.ru/author.aspx?id={handle}', true),
('hsin', 'COCI', 'https://hsin.hr/coci/', true),
('ioi', 'IOI', 'https://stats.ioinformatics.org/people/{handle}', true),
('algotester', 'Algotester', 'https://algotester.com/en/User/Profile/{handle}', true),
('cphof', 'CP Hall of Fame', 'https://cphof.org/profile/{handle}', true),
('opencup', 'Open Cup', 'https://opencup.ru/', true),
('robocontest', 'Robocontest', 'https://robocontest.uz/profile/{handle}', true),
('ucup', 'Universal Cup', 'https://ucup.ac/user/{handle}', true),
('acmu', 'ACM.U', 'https://acmu.ru/user/{handle}', true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  profile_url_template = EXCLUDED.profile_url_template,
  is_active = EXCLUDED.is_active;
